adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.users, name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
]

authapp/urls.py
from django.urls import path
from django.urls import re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf.urls import include
from django.conf.urls import include
from django.urls import re_path


urlpatterns = [
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^products/', include('mainapp.urls', namespace='products')),
    re_path(r'^contact/', mainapp.contact, name='contact'),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^admin/', include('adminapp.urls', namespace='admin')),
    path('', include('social_django.urls', namespace='social')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
import mainapp.views as mainapp
from django.urls import re_path

app_name = "mainapp"

urlpatterns = [
    re_path(r'^$', mainapp.products, name='index'),
    re_path(r'^category/(?P<pk>\d+)/$', mainapp.products, name='category'),
    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),
    re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.products, name='page'),
]

ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path

app_name= "ordersapp"

urlpatterns = [
   re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
   re_path(r'^forming/complete/(?P<pk>\d+)/$',
           ordersapp.order_forming_complete, name='order_forming_complete'),
   re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(),
           name='order_create'),
   re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(),
           name='order_read'),
   re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(),
           name='order_update'),
   re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(),
           name='order_delete'),
]

mainapp/models.py
from django.db import models
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

mainapp/views.py
from django.shortcuts import render
from .models import ProductCategory, Product
from django.shortcuts import get_object_or_404
from basketapp.models import Basket
import random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.all()

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category). \
                        exclude(pk=hot_product.pk)[:3]

    return same_products


def contact(request):
    return render(request, 'mainapp/contact.html')


def main(request):
    title = 'GeekShop'

    products = Product.objects.all()[:4]

    content = {'title': title, 'products': products}
    return render(request, 'mainapp/index.html', content)


def products(request, pk=None, page=1):
    title = 'продукты'
    links_menu = ProductCategory.objects.filter(is_active=True)
    basket = get_basket(request.user)

    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = Product.objects.filter(is_active=True, \
                                              category__is_active=True).order_by('price')
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk, \
                                              is_active=True, category__is_active=True).order_by('price')

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
            'basket': basket,
        }

        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
        'basket': basket,
    }

    return render(request, 'mainapp/products.html', content)


def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
    }

    return render(request, 'mainapp/product.html', content)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>

{% load static%}

<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block title %}
        <title>Title</title>
    {% endblock %}

    {% block css %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

</head>
<body>
{% block container %}

{% endblock %}

{% block footer %}

{% endblock %}
</body>
</html>

mainapp/templates/mainapp/contact.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Контакты</title>
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">
	<link rel="stylesheet" href="/static/fonts/font-awesome/css/font-awesome.css">
</head>
<body>
	<div class="container">
		<div class="hero">
			<div class="header clearfix">
				<a href="index.html" class="logo"></a>
				<ul class="menu">
					<li><a href="/" class="active">домой</a></li>
					<li>
					  <a href="{% url 'products:index' %}"
						 class="{% if request.resolver_match.namespace == 'products' %}
								  active
								{% endif %}">
						продукты
					  </a>
					</li>
					<li><a href="{% url 'contact' %}">контакты</a></li>
					{% if user.is_authenticated %}
					<li>
							<a href="{% url 'auth:edit' %}">
								{{ user.first_name|default:'Пользователь' }}
							</a>
					</li>
					{% endif %}
					<li>
						{% if user.is_authenticated %}
						 <a href="{% url 'auth:logout' %}">выйти</a>
						{% else %}
						 <a href="{% url 'auth:login' %}">войти</a>
						 <a href="{% url 'auth:register' %}">регистрация</a>
						{% endif %}
					</li>
				</ul>
				</ul>
				<a href="#" class="search"></a>
				<a href="{% url 'basket:view' %}" class="basket">
				  <span>
					{% if basket %}
					  {{ basket.0.total_cost|floatformat:0 }} руб
					  ({{ basket.0.total_quantity }} шт)
					{% endif %}
				  </span>
				</a>
			</div>
			<h1>наши контакты</h1>
		</div>

		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>

		<div class="clr"></div>
	</div>	

    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>	
			
</body>
</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block title %}
           {{ title|capfirst }}
{% endblock %}


{% block css %}
       <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
       <link href="{% static  'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
       <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
       <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
{% endblock %}
{% block js %}
       <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
       <script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock %}



{% block container %}
	<div class="container">
		<div class="slider">

			<div class="header clearfix">
				<a href="index.html" class="logo"></a>
				<ul class="menu">

					<li><a href="/" class="active">домой</a></li>
					<li>
					  <a href="{% url 'products:index' %}"
						 class="{% if request.resolver_match.namespace == 'products' %}
								  active
								{% endif %}">
						продукты
					  </a>
					</li>
					<li>
					   <a href="{% url 'contact' %}" class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
						   контакты
					   </a>
					</li>
					{% if user.is_authenticated %}
						   <li class="nav-item">
							   <div class="dropdown">
								   <a class="nav-link dropdown-toggle" href="" data-toggle="dropdown">
									   {{ user.first_name|default:'Пользователь' }}
									   <span class="caret"></span>
								   </a>
								   <ul class="dropdown-menu">
									   <li>
										   <a href="{% url 'auth:edit' %}">
											   профиль
										   </a>
									   </li>
									   <li>
										   <a href="{% url 'ordersapp:orders_list' %}">
											   заказы
										   </a>
									   </li>
								   </ul>
							   </div>
						   </li>
					{% endif %}
					{% if user.is_superuser %}
					   <li>
						   <a href="{% url 'admin:users' %}">админка</a>
					   </li>
					{% endif %}
					<li>
						{% if user.is_authenticated %}
						 <a href="{% url 'auth:logout' %}">выйти</a>
						{% else %}
						 <a href="{% url 'auth:login' %}">войти</a>
						 <a href="{% url 'auth:register' %}">регистрация</a>
						{% endif %}
					</li>
				</ul>
				</ul>
				<a href="#" class="search"></a>
				<a href="{% url 'basket:view' %}" class="basket">
				  <span>
					{% if basket %}
					  {{ basket.0.total_cost|floatformat:0 }} руб
					  ({{ basket.0.total_quantity }} шт)
					{% endif %}
				  </span>
				</a>

			</div>

			<div class="text-slider">

				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.  </p>
				<h3 class="red">Сейчас  {% now "d M Y" %} </h3>
				<!--p>Работа с тегами, вывод текущей даты</p-->
				<a href="#" class="button-order">заказать <img src="/static/img/arrow.png" alt=""></a>
			</div>

			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>

		</div>

		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static "img/arrow.png" %}" alt="My image"></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
					{% for product in products %}
					  <div class="block">
						<a href="#">
						  <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
						  <div class="text">
							<h3>{{ product.category.name }}</h3>
							<h4>{{ product.name }}</h4>
							<p>{{ product.description }}</p>
						  </div>
						</a>
					  </div>
					{% endfor %}
			</div>
		</div>

		<div class="clr"></div>

	</div>
{% endblock %}

{% block footer %}
	<div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
      <div class="details-slider">
        <div class="slider-product">
          <img src="/media/{{ product.image }}" 
               alt="{{ product.short_desc }}">
        </div>
        <div class="slider-control">
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 1">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 2">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 3">
            </a>
          </div>
        </div>
      </div>

      <div class="description">
        <h3 class="big-bold">{{ product.name }}</h3>
        <br>
        <p class="price"> {{ product.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' product.pk %}" class="red-button">
          заказать 
          <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
          {{ product.description }}
        </div>
      </div>
    </div>

  </div>

  <div class="clr"></div>

{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static%}


	{% block title %}
        <title>Каталог</title>
    {% endblock %}

    {% block css %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}


{% block container %}
	<div class="container">
		<div class="hero-white">
			<div class="header clearfix">
				<a href="index.html" class="logo"></a>
				<ul class="menu">
					<li><a href="/" class="active">домой</a></li>
					<li>
					  <a href="{% url 'products:index' %}"
						 class="{% if request.resolver_match.namespace == 'products' %}
								  active
								{% endif %}">
						продукты
					  </a>
					</li>
					<li><a href="{% url 'contact' %}">контакты</a></li>
					{% if user.is_authenticated %}
					<li>
							<a href="{% url 'auth:edit' %}">
								{{ user.first_name|default:'Пользователь' }}
							</a>
					</li>
					{% endif %}
					<li>
						{% if user.is_authenticated %}
						 <a href="{% url 'auth:logout' %}">выйти</a>
						{% else %}
						 <a href="{% url 'auth:login' %}">войти</a>
						 <a href="{% url 'auth:register' %}">регистрация</a>
						{% endif %}
					</li>
				</ul>
				<a href="#" class="search"></a>
				<a href="{% url 'basket:view' %}" class="basket">
				  <span>
					{% if basket %}
					  {{ basket.0.total_cost|floatformat:0 }} руб
					  ({{ basket.0.total_quantity }} шт)
					{% endif %}
				  </span>
				</a>


			</div>
		</div>

		<div class="details">
			<div class="links clearfix">
				<ul class="links-menu">
				  <li>
					<a href="{% url 'products:category' 0 %}"
					   class="{% if request.resolver_match.kwargs.pk == '0' %}
								active
							  {% endif %}">
					  все
					</a>
				  </li>
				  {% for link in links_menu %}
					<li>
					  <a href="{% url 'products:category' link.pk %}"
						 class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
								  active
								{% endif %}">
						{{ link.name }}
					  </a>
					</li>
				  {% endfor %}
				</ul>
			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
					  <img src="/media/{{ hot_product.image }}">
					</div>
					<div class="slider-control">
					  <div class="block">
						<a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
					  </div>
					  <div class="block">
						<a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
					  </div>
					  <div class="block">
						<a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
					  </div>
					</div>
				  </div>

				  <div class="description">
					<h3 class="big-bold">{{ hot_product.name }}</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price">{{ hot_product.price }} <span>руб</span></p>
					<a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
					  заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
					  {{ hot_product.description }}
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static "img/arrow.png" %}" alt="My image">
				</div>
				<div class="related-products clearfix">
					{% for product in same_products %}

						<div class="block">
						<a href="#">
						  <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
						  <div class="text">
							<h3>{{ product.category.name }}</h3>
							<h4>{{ product.name }}</h4>
							<p>{{ product.description }}</p>
						  </div>
						</a>
					  </div>

					{% endfor %}

				</div>
			</div>
		</div>

		<div class="clr"></div>

	</div>
{% endblock %}

{% block footer %}
	<div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
  <div class="hero-white">
    <div class="header clearfix">
      {% include 'mainapp/includes/inc_menu.html' %}
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="products_list">
      <div class="title clearfix">
        <h2>Категория: "{{ category.name|title }}"</h2>
        <div class="paginator">
          {% if products.has_previous %}
            <a href="{% url 'products:page'
                             category.pk products.previous_page_number %}">
              <
            </a>
          {% endif %}
          <span class="current">
            страница {{ products.number }} из
            {{ products.paginator.num_pages }}
          </span>
          {% if products.has_next %}
            <a href="{% url 'products:page'
                             category.pk products.next_page_number %}">
              >
            </a>
          {% endif %}
        </div>
      </div>
      <div class="category-products clearfix">
        {% for product in products %}
            <div class="block">
              <a href="{% url 'basket:add' product.pk %}">
                <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                <div class="text">
                  <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                  <h4>{{ product.name }}</h4>
                  <p>{{ product.description }} </p>
                </div>
              </a>
            </div>
          {% endfor %}
        </div>
    </div>
  </div>

  <div class="clr"></div>

{% endblock %}